### ISSUE TITLE
How to have test cases for models in KerasFuse?

### ISSUE THREAD

**Issue by ash-01xor** [ayyucedemirbas/KerasFuse#15]
Hey @onuralpszr @ayyucedemirbas, while contributing to the models in this repository had this question regarding testing them. Is the library being planned in such a way that individual test cases need to be present for each model being implemented?

Thanks for your time.

**Comment by onuralpszr** [comment]
Let's say we complete a certain feature or model, we can download and do short CPU based tests and certain tests may require GPU based tests for that I had some ideas where to use "free" for publics repos, but for example I added MLP tests and I shorten the epoch number because github action doesn't have GPU and we cannot afford very long epoch tests so I had to minimize and make sure "it is fine based on epoch we given" but naturally we should test on our GPU cards etc. (If we can or person can) 

I hope that answer some of it :)

**Comment by ash-01xor** [comment]
Doesn't this sort of downloading and running the script of a model on a dataset take time, is this an efficient process?
or is there a better alternative in terms of unit tests for each model as such?

**Comment by onuralpszr** [comment]
> Doesn't this sort of downloading and running the script of a model on a dataset take time, is this an efficient process? or is there a better alternative in terms of unit tests for each model as such?

Github action download speed is fast, don't worry about that part. Secondly,  what I think of on top my of head is I can split tests in github actions and testing faster.

**Comment by ash-01xor** [comment]
Well thanks for letting me know, this gives some sort of clarity . Will help in contributing to the models.
